### ISSUE TITLE
Resources$NotFoundException on pre-lollipop devices

### ISSUE THREAD

**Issue by michaelbukachi** [TonnyL/WhatsNew#6]
I got the following crash when trying to run on pre-lollilop devices:
```
Fatal Exception: android.content.res.Resources$NotFoundException: File res/drawable/ic_calendar_range.xml from drawable resource ID #0x7f080086. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
       at android.content.res.Resources.loadDrawable(Resources.java:2974)
       at android.content.res.Resources.getDrawable(Resources.java:1558)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:465)
       at io.github.tonnyl.whatsnew.adapter.ItemsAdapter.onBindViewHolder(ItemsAdapter.kt:26)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onCreateViewHolder(RecyclerView.java:6823)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
       at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
       at android.view.View.measure(View.java:16831)
       at android.widget.RelativeLayout.measureChild(RelativeLayout.java:698)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:494)
       at android.view.View.measure(View.java:16831)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16831)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16831)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16831)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2586)
       at android.view.View.measure(View.java:16831)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2189)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1352)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1535)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
On further investigation I found the cause of the error was the line below:
```
class ItemsAdapter(private val mData: Array<WhatsNewItem>, private val mContext: Context) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {

    var titleColor: Int = Color.BLACK
    var contentColor: Int = Color.parseColor("#808080")
    var iconColor: Int = Color.BLACK

    override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {
        if (position <= mData.size) {
            with(holder as ItemViewHolder) {
                with(itemView) {
                    mData[position].imageRes?.let {
               ---->      ContextCompat.getDrawable(mContext, it)?.let { drawable ->
                            DrawableCompat.setTint(drawable, iconColor)
                            itemTitleTextView.setCompoundDrawablesWithIntrinsicBounds(drawable, null, null, null)
                        }
}
......
```
From [this answer](https://stackoverflow.com/a/48237058/3716006) it seems ContextCompat.getDrawable won't work with vector drawables unless `AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);` is set. I would recommend replacing `ContextCompat` with `AppCompatResources` so that consumers of your library aren't forced to use `AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);` in their Application classes. Hopefully, I'll be able to make a pull request some time this week.

**Comment by TonnyL** [comment]
OK, cool, glad to see your pr 😃
